### PR TITLE
Start events section

### PR DESCRIPTION
**Pull request by ct-martin**
Creates section to start working on content. Progress on #157 but does not complete.

Sample event of Tim @ Flock; please don't block the PR on that event but rather on the functionality.

### CODE REVIEW

**Comment by jwflory** [comment]
I'll try to review this over the weekend. I noticed this includes a write-up of Flock from @Tjzabel. I figure he should probably review this PR at a minimum too.

**Comment by ct-martin** [comment]
@jwflory The Flock post's quote at the bottom was copy-pasted from the event page, so if the description at the top & the title are acceptable I'd like to not block this PR on it. If significant revision (more than a typo or two) is desired I'd rather have a follow-up issue or PR since I needed sample content but this PR is for the site functionality.

**Comment by jwflory** [comment]
> If significant revision (more than a typo or two) is desired I'd rather have a follow-up issue or PR since I needed sample content but this PR is for the site functionality.

@ct-martin I missed your original comment noting this. Makes sense. @Tjzabel can update it later if something is missing or incorrect.

**Comment by ct-martin** [comment]
@jwflory for the high-level, it works exactly like regular posts except for a different folder and that I've been working on custom metadata (YAML front matter). This is sort of an MVP, expect more changes later. Technically these are posts as Jekyll sees them, but of the category "events"

**Pull request merged**
