### PR TITLE
ImagineRIT 2018 Updates & Reskinning

### PR DESCRIPTION
**Pull request by ct-martin**
* Updates many dependencies, hopefully will stop nokogiri complaints (NOT the fix for #148, but helps temporarily mitigate effects)
* Gets rid of the (in my opinion and some others) ugly brown we're using in the theme
* Cleaned up the templates slightly by using inheritance
* Full RITlug banner; by using the horizontal one instead of the vertical it doesn't force the icon and the RITlug name to share the limited height

**Requesting feedback/discussion**

_Going to be talking with @gen1e in FOSS Hours about the white-on-white background which already exists in our current theme, but became more visibly noticeable when introducing the white in the navbar and I'm not liking it. Currently debating deeper shadow on content and using `mdl-color--grey-(100|200)` (light grey) on the main background behind the content as options. The latter makes the white on the navbar a little odd though, but since the banner doesn't have white filler the grey makes that feel odd._

screen shot 2018-04-24 at 22 58 14

### CODE REVIEW

**Comment by gen1e** [comment]
Yes that last comment with the updated one was exactly what I was thinking of! The light grey on the background of the page I really like. I also like the orange at the top, this way there is a bit less white overwhelming the page. I would maybe use a slightly more off black on the nave bar as it feels a little too black, but that's me being super picky, otherwise I think it's awesome.

**Comment by ct-martin** [comment]
New commit changes to the color scheme in the 2nd screenshot. I'm still going to talk with @gen1e about this later, but it'd rather have something nicer and have it pulled than bikeshedding.

**Comment by ct-martin** [comment]
Update: current color schemes:

screen shot 2018-04-25 at 15 56 48
screen shot 2018-04-25 at 15 56 57
screen shot 2018-04-25 at 15 57 07

**Comment by ct-martin** [comment]
@jpazer suggested tweaking the logo colors a little and I ended up playing with it a bit more beyond that

screen shot 2018-04-26 at 22 39 53
@jpazer++ although I think the orange is feeding off the navbar and being a little too strong

screen shot 2018-04-26 at 22 41 00
Swapped the white and orange, looks decent but the black and orange are slightly difficult to read

screen shot 2018-04-26 at 22 52 31
Made the text white. The white is feeding off the other white in the page a little, but I think it looks a little nicer than the plain white

screen shot 2018-04-26 at 22 44 32
Threw the 2nd one into the monochrome on a whim, not really a fan though

**Comment by ct-martin** [comment]
Note to self when I look at some more stuff in fall: the white-based one looks very nice on a monitor but gets totally washed out on the bad/uncalibrated projectors on campus

**Pull request merged**
