### PR TITLE
Created ssh talk entry for website.

### PR DESCRIPTION
**Pull request by jrtechs**
Added the SSH talk to the website.

### CODE REVIEW

**Comment by Tjzabel** [comment]
CodeClimate is still expecting to be used here... I'm really not sure why.

I would *assume* GitHub is picking up any dotfiles within our root directory to determine which CI method to use. @jwflory @ct-martin do either of you by any chance know why CodeClimate is still being pulled in here?

Since no RITlug repository currently uses CodeClimate as a CI platform anymore, I can simply take off the CC GitHub app from the RITlug org, but I'd rather know why it's still pulling it in.

**Comment by ct-martin** [comment]
@Tjzabel repo settings, probably webhooks

**Comment by Tjzabel** [comment]
@ct-martin hmm, very odd, but we don't have any webhooks that have anything to do with CC. I ended up just removing it from our list of GH Apps since we don't use it anymore, and I don't think we should plan on using it in the future.

**Comment by Tjzabel** [comment]
Anywho, CC has nothing to do with this PR.

Merging :tada:

**Comment by jwflory** [comment]
> Since no RITlug repository currently uses CodeClimate as a CI platform anymore

CodeClimate isn't a CI platform, it's a code introspection tool. :slightly_smiling_face: 

At one point it was used to evaluate code cleanliness and best practices of this website, but this stopped working at some point. I can't remember when it was or what exactly happened though.

**Comment by Tjzabel** [comment]
@jwflory ah, I mis-typed what it was. I *did* also think it did CI, so thanks for the clarification :+1: 

I believe we stopped using CC when we switched the site to Jekyll. I'm just really wondering why this repo still is trying to run the CC introspection when there are no CC files in the repo.

**Comment by Tjzabel** [comment]
As a side note, I disabled CC for the entire org, but I realized that TeleIRC still makes use of CC in order to determine code coverage. However, as we start porting to Go, the coverage info won't be useful at all, so I am going to leave that be for now.

**Comment by jwflory** [comment]
> However, as we start porting to Go, the coverage info won't be useful at all, so I am going to leave that be for now.

This is off-topic, but there are some Go-specific tools I see widely used in the k8s community for code quality and introspection, so we can explore there when the time comes.

**Comment by Tjzabel** [comment]
Absolutely! I would love to make use of code coverage, but JS-formatted coverage isn't helpful for us at this stage :P

**Pull request merged**
