### PR TITLE
update to hosted MDL v1.3.0, fixes issue #23

### PR DESCRIPTION
**Pull request by patkub**

### CODE REVIEW

**Comment by Serubin** [comment]
Is there a good way to test view a branch before pulling into master with github pages?

**Comment by patkub** [comment]
Use travis ci tests?

**Comment by Serubin** [comment]
I'm not familiar with github pages or similar markdown styles sites, could you point me in the direction of instructions?

Thank you!

**Comment by deejoe** [comment]
GitHub's backend for this is Jekyll:

https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Pull request merged**
