### PR TITLE
Add week 4 meeting.

### PR DESCRIPTION
**Pull request by Tjzabel**
This PR adds this week's email announcement.

### CODE REVIEW

**Comment by ct-martin** [comment]
Otherwise LGTM though

**Comment by Tjzabel** [comment]
@ct-martin fixed

**Comment by Tjzabel** [comment]
@ct-martin @jrtechs so, just so I'm clear, this will then go out onto the mailing list, but also needs to be put through CampusGroups, correct?

**Comment by ct-martin** [comment]
Yes, the Google Group is automated but it needs to manually be sent on
CampusGroups and Slack (although we might be able to find a bit for the
latter).

--
Christian Martin (Phone)

**Pull request merged**
