### PR TITLE
added telegram group to get involved page

### PR DESCRIPTION
**Pull request by abkahrs**

### CODE REVIEW

**Comment by repkam09** [comment]
@abkahrs Seems reasonable to me

**Comment by thenaterhood** [comment]
I'll leave this to the discretion of next year's eboard @jflory7 and @Serubin since moderator responsibility will fall to them. Which reminds me to give them a couple heads up about things.

Freenode IRC is public by nature, but we do moderate who joins some of our other things because of past issues. We may want to extend that policy to Telegram but again, I'll leave it up to next year's eboard.

**Comment by Serubin** [comment]
I wonder if we can create a request link rather than a join link. Having that sort of link online may lead to strays

**Comment by jflory7** [comment]
As far as Telegram goes, it's either have a public invite link or do not have one. That's interesting about the past issues, but I also feel like it wouldn't be a problem given the nature of Telegram. I'm personally all aboard merging this in.

**Comment by Serubin** [comment]
I'm voting to merge.

**Comment by jflory7** [comment]
:clapper: Here we go!

**Comment by thenaterhood** [comment]
Weeeeee! Mergin' https://drive.google.com/file/d/0B4icTp-noXHbc1lsd1BCc2ZlRTg/view?usp=sharing

**Pull request merged**
