### PR TITLE
End-to-end tests for Jekyll in CircleCI

### PR DESCRIPTION
**Pull request by patkub**
This runs rspec tests on headless chrome  (aka no GUI, all in memory) in circleci. See `rspec-tests` step [here](https://circleci.com/gh/patkub/ritlug.github.io/42).

```#!/bin/bash -eo pipefail
bundle exec rspec
Configuration file: /home/circleci/project/_config.yml
Generating site: /home/circleci/project -> /home/circleci/project/_site
..................

Finished in 8.49 seconds (files took 1.11 seconds to load)
18 examples, 0 failures

### CODE REVIEW

**Comment by patkub** [comment]
Thanks. @jflory7 what do you think?

**Comment by patkub** [comment]
I think you can use the "Squash and merge" option to merge all of these commits as one commit. I started a wiki page [here](https://github.com/RITlug/ritlug.github.io/wiki/Jekyll-Tests) which I'll work on elaborating next week.

**Comment by patkub** [comment]
I combined some of the commits related to the rspec tests.

**Comment by Serubin** [comment]
This looks awesome @patkub.

**Comment by patkub** [comment]
@Serubin Thanks! Are the commits ok? A lot of the commits are merged from upstream.

**Comment by Serubin** [comment]
I haven't had time to look through them - but I will as soon as I have time.

**Comment by Serubin** [comment]
Everything looks golden. I have no idea how to "review" and accept...

**Comment by Serubin** [comment]
@patkub Looks like ci/circleci is still waiting on something - is there a way to force it to do what it needs too?

**Comment by patkub** [comment]
@Serubin looks like a bug, https://discuss.circleci.com/t/ci-circleci-waiting-for-status-to-be-reported-on-inherited-project/6345. Try clicking the settings icon in the top right, unfollow the project and refollow.

**Comment by patkub** [comment]
I think this might need to be merged for a ci status to be reported. CircleCI is passing on my rspec-tests branch here: https://circleci.com/gh/patkub/workflows/ritlug.github.io/tree/rspec-tests.

**Comment by Serubin** [comment]
@patkub Still can't get it to merge.

**Comment by axk4545** [comment]
@patkub where are we on this?

**Comment by patkub** [comment]
@Serubin @axk4545 we need to manually merge this with `git merge rspec-tests` on master branch for a CI status to be reported.

**Comment by axk4545** [comment]
@patkub so it is a github/PR bug then?

**Comment by patkub** [comment]
@axk4545 There are two issues now.

1. `ci/circleci — Waiting for status to be reported`
This is a github/PR bug due to changes in the circleci config, which means we need to manually merge for the status to be reported.

2.  `ci/circleci: test — Your tests failed on CircleCI`. Click on Details to see the latest build on this branch.

**Comment by Serubin** [comment]
@jflory7 Dismissing your review, I'll squash stuff as I see fit.

**Comment by patkub** [comment]
@Serubin give me a few minutes and I'll fix the tests for renamed  The Link => Campus Groups. Then you need to manually merge because github/pr bug.

**Comment by Serubin** [comment]
@patkub Too late. Do another PR please.

**Comment by patkub** [comment]
@Serubin @axk4545 Tests are passing now.

**Comment by patkub** [comment]
@Serubin What do you mean about making another PR? All of this is in my rspec-tests branch that I want to merge in.

**Comment by patkub** [comment]
@Serubin I squashed everything I could.

**Comment by Serubin** [comment]
@jflory7 Squashing further is painful - is this looking okay to you?

**Comment by patkub** [comment]
@Serubin Due to the ci status bug, you can temporarily disable status checks and merge this on GitHub.
https://help.github.com/articles/enabling-required-status-checks/

**Comment by Serubin** [comment]
@patkub Once @jflory7 signs off I'll merge manually.

**Comment by jflory7** [comment]
Hey @patkub, I talked with @Serubin about this one and since this PR includes commits that are already in the main repo and it's confusing about what's being merged in or not, we decided to go ahead and close this one, and you can resubmit the changes via new PR. It'll be easier to review this in a new PR.

Also, when making your PRs, please be sure to file different PRs for doing different things. It makes them easier to review and hopefully will prevent situations like this from coming up in the future. Thanks!

**Pull request closed without merging**
