### PR TITLE
[talks] systemd: add post and slides for Garret Arcoraci

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds a new post and the provided slides for Garret's
presentation on systemd, from 2019 January 25. Redistributed on
ritlug.com with permission.

### CODE REVIEW

**Comment by Tjzabel** [comment]
@jwflory thanks! However, I'm not sure we need the `.pptx` powerpoint slide. We only need the PDF of the slides.

**Comment by jwflory** [comment]
Is there a specific reason you don't want the source document available on the website? I figured it would be helpful to make the source available for future remixing. If you still want me to remove it, I can.

**Comment by Tjzabel** [comment]
@jwflory the source isn't available just because it isn't necessary. The PDF can be downloaded once available.

**Comment by ct-martin** [comment]
Agreed, as the site is now there isn't a good place for it and it doesn't integrate well. However, I also agree it would be nice to share the source. Maybe a shared folder on Nextcloud if/when we ever get it done?

**Comment by deejoe** [comment]
On Mon, Jan 28, 2019 at 08:37:34PM -0800, Christian Martin wrote:
> Agreed, as the site is now there isn't a good place for it and it doesn't
> integrate well. However, I also agree it would be nice to share the source.
> Maybe a shared folder on Nextcloud if/when we ever get it done?

What about just having it in the repo? That seems the most natural place to me for hosting an "editable" version of anything.

Does it need to be on the rendered downstream site?

-- 
Joe

**Comment by Tjzabel** [comment]
@deejoe it's certainly a possibility we can just make a folder/repo to host all the `.pttx` powerpoint files we currently have on our Google Drive.

At the moment, I'm not sure the best way to go about making all our presentation files readily available. At the very least, the PDF is available from most of them on our website.

**Comment by ct-martin** [comment]
@tjzabel @deejoe @jwflory how about merging this without the PPTX and filing an issue to find a permanent, public location for talk sources?

**Comment by Tjzabel** [comment]
@ct-martin that works for me :+1:

**Comment by jwflory** [comment]
Dropped the PPTX file and rebased to current `HEAD`. Should be ready to merge.

**Pull request merged**
