### PR TITLE
Action borders

### PR DESCRIPTION
**Pull request by patkub**
border for action buttons, and button ripple effect

### CODE REVIEW

**Comment by jflory7** [comment]
Hi @patkub! Thanks for submitting this, and sorry for the incredibly long delay on getting this reviewed… I guess I missed the email.

@Serubin I'm not much of a web dev guy, but this looks fairly simple. Shall we merge it in?

@thenaterhood Also, I vaguely remember us having a discussion about setting up some sort of CI/CD pipeline for testing the website and viewing changes in a browser. Was there something we could use to accomplish this? I can look into setting it up, but I figured I'd ask for a pointer for traveling down a rabbit hole.

**Comment by jflory7** [comment]
Also, anyone in @RITlug/eboard is welcome to review this too or give a 👍 to merge. I mostly want to just get another person to peek in before merging.

**Comment by patkub** [comment]
Hey @jflory7! I think I had a demo of this up on my server, but it's down right now.

About CI/CD pipelines. We can test if Jekyll builds the site without error in a CI. I setup a test in circleci here (might need to login with github to circleci in order to view it):
https://circleci.com/gh/patkub/ritlug.github.io/ 

Travis CI supports running Firefox and Chrome in headless browser mode. This lets you run tests on a CI that would normally require a GUI. More information here: https://docs.travis-ci.com/user/gui-and-headless-browsers/  

We could also automatically git push to the github-pages branch from within the CI after tests succeed.

**Comment by jflory7** [comment]
@patkub Thanks again for your work on this here, and sorry for the delay. 😄 For the CI discussion, will pick this up in the other PR!

**Pull request merged**
