### PR TITLE
About & Affiliates

### LINKED ISSUE #175: Re-design the "about" and "getting involved" pages
* Formally merge `/about` & `/get-involved`, or split the content to make proper pages for both
* Make prettier, like done for the home & TigerOS pages
* Depending on RITlug/tasks#84, ability to add affiliate/sponsor links
* New template with quick details sidebar that contains meeting time/place and other info?

### LINKED ISSUE #179: Add StickerMule logo as affiliated partner to home page
We need to add a new logo somewhere on our home page with the [official StickerMule logo](https://www.stickermule.com/press). When clicked, the logo should point to this link:

`https://www.stickermule.com/supports/you`

This can be a short-term implementation to get something there for now, and we can polish it up once we have a chance to catch our breath later this semester or next.

### PR DESCRIPTION
**Pull request by ct-martin**
DOES NOT CLOSE #175 

* Revises "About" page
* Fixes #179

### CODE REVIEW

**Comment by ct-martin** [comment]
@jrtechs my dev env did a stupid, can you double-check that this works?

**Comment by Tjzabel** [comment]
Also leaving an error that popped up while I was looking at the devel site: 

`[2018-11-16 20:23:05] ERROR `/favicon.ico' not found.`

**Comment by ct-martin** [comment]
Ok, that fixes the home page. Personally I think the "About" should go first, at least for MakerFaire. Anyone else on eboard is welcome to chime in, but tomorrow morning this is going to be merged if there are no other blocking issues.

**Comment by ct-martin** [comment]
For the record, vertical alignment is a pain, I'm not super motivated to
fix that in the near future

--
Christian Martin (Phone)

**Pull request merged**
