### PR TITLE
Add teleirc logo

### PR DESCRIPTION
**Pull request by thenaterhood**
May as well, since we've got one

### CODE REVIEW

**Comment by Tjzabel** [comment]
@ct-martin what else do we need in order to make the TeleIRC logo show up? This PR didn't change anything.

**Comment by Tjzabel** [comment]
Oh. The logo is showing up, but it's super blurry

**Comment by Tjzabel** [comment]
Ah, found the issue. @thenaterhood we need to use the SVG version in order for the logo to show up properly.

**Comment by ct-martin** [comment]
@thenaterhood so the `images` frontmatter integrated with SEO and the `gallery` partial template. You need to add the gallery, even if there's only one image

**Comment by Tjzabel** [comment]
@ct-martin what do you mean add the gallery? That would look super weird with the TeleIRC logo.

**Comment by ct-martin** [comment]
@Tjzabel https://github.com/RITlug/ritlug.github.io/blob/9fade6aa74dc2c8867166fd6224e8b7708eb7b73/projects/_posts/2018-01-02-tigeros.html#L33-L35

it's smart enough to know if you don't have more than one image and then not act like a carousel. what you did works perfectly fine, but you asked why Nate's PR didn't work

**Comment by Tjzabel** [comment]
@ct-martin ah. His PR ended up working fine, it just took a while for the image to build.

**Pull request merged**
